### ISSUE TITLE
Does this solve the issues with OpenGL?

### ISSUE THREAD

**Issue by arximboldi** [ralismark/nix-appimage#5]
This looks very promising. Have been looking for ages for a solution to generate working for generating appimage applications for OpenGL applications. `nix-bundle` has [issues with it](https://github.com/matthewbauer/nix-bundle/issues/23) all attempts to find a workaround (documented in that thread and related PRs) have failed for me.

This project, due to it's ability to not bring glibc, looks promising. However since it doesn't include a desktop file, maybe it is not intended to fix the OpenGL issue? Is this supported or part of the road-map?

**Comment by arximboldi** [comment]
I gave this a try today. When I try to run the generated image on NixOS I get an error:
```
appimage-run myapp-x86_64.AppImage 
Unsupported AppImage Type: 32
```

**Comment by ralismark** [comment]
Hi, the `Unsupported AppImage Type` is an error with this project that I've fixed with https://github.com/ralismark/nix-appimage/commit/9f2cace67953e650914157108420c58eece060c8 -- thanks for letting me know!

Regarding OpenGL, this doesn't do anything special to make those apps work on non-NixOS. So you'll still need to use e.g. [nixGL](https://github.com/guibou/nixGL). I don't currently have plans to address the issue with this project, since I feel it's a bit out of scope.

**Comment by arximboldi** [comment]
Hi @ralismark: sorry for the late reply but I think it is sadly it should be within the scope of the project, as it is not possible to use `nixGL` on the foreign system where the `appimage` is run (onless of course they have Nix, but that defeats the purpose of distributing an `appimage`).

**Comment by ralismark** [comment]
for the record, the main issue discussing this problem is

- https://github.com/NixOS/nixpkgs/issues/9415
